/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AuthenticatedCriacaoRouteImport } from './routes/_authenticated/criacao'
import { Route as AuthenticatedEstatisticasRouteImport } from './routes/_authenticated/estatisticas'
import { Route as AuthenticatedFlashcardsRouteImport } from './routes/_authenticated/flashcards'
import { Route as AuthenticatedRevisoesRouteImport } from './routes/_authenticated/revisoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCriacaoRoute = AuthenticatedCriacaoRouteImport.update({
  id: '/criacao',
  path: '/criacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstatisticasRoute =
  AuthenticatedEstatisticasRouteImport.update({
    id: '/estatisticas',
    path: '/estatisticas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFlashcardsRoute = AuthenticatedFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisoesRoute = AuthenticatedRevisoesRouteImport.update({
  id: '/revisoes',
  path: '/revisoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criacao': typeof AuthenticatedCriacaoRoute
  '/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/revisoes': typeof AuthenticatedRevisoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criacao': typeof AuthenticatedCriacaoRoute
  '/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/revisoes': typeof AuthenticatedRevisoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/_authenticated/criacao': typeof AuthenticatedCriacaoRoute
  '/_authenticated/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/_authenticated/flashcards': typeof AuthenticatedFlashcardsRoute
  '/_authenticated/revisoes': typeof AuthenticatedRevisoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/criacao'
    | '/estatisticas'
    | '/flashcards'
    | '/revisoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/criacao'
    | '/estatisticas'
    | '/flashcards'
    | '/revisoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/configuracoes'
    | '/_authenticated/criacao'
    | '/_authenticated/estatisticas'
    | '/_authenticated/flashcards'
    | '/_authenticated/revisoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/criacao': {
      id: '/_authenticated/criacao'
      path: '/criacao'
      fullPath: '/criacao'
      preLoaderRoute: typeof AuthenticatedCriacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estatisticas': {
      id: '/_authenticated/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof AuthenticatedEstatisticasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flashcards': {
      id: '/_authenticated/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisoes': {
      id: '/_authenticated/revisoes'
      path: '/revisoes'
      fullPath: '/revisoes'
      preLoaderRoute: typeof AuthenticatedRevisoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCriacaoRoute: typeof AuthenticatedCriacaoRoute
  AuthenticatedEstatisticasRoute: typeof AuthenticatedEstatisticasRoute
  AuthenticatedFlashcardsRoute: typeof AuthenticatedFlashcardsRoute
  AuthenticatedRevisoesRoute: typeof AuthenticatedRevisoesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCriacaoRoute: AuthenticatedCriacaoRoute,
  AuthenticatedEstatisticasRoute: AuthenticatedEstatisticasRoute,
  AuthenticatedFlashcardsRoute: AuthenticatedFlashcardsRoute,
  AuthenticatedRevisoesRoute: AuthenticatedRevisoesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
